name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9","3.10","3.11","3.12","3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e .

      - name: Run tests
        run: pytest -q


      - name: Smoke demo (only on 3.12)
        if: matrix.python-version == '3.12'
        env:
          MPLBACKEND: Agg
        run: python examples/demo_var_game.py --N 4 --T 120 --p 2 --k 3 --ridge 1e-3 --seed 0
  notebooks:
    name: Notebooks (fast)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install package + notebook deps
        run: |
          python -m pip install -U pip
          pip install -e .
          pip install -r requirements-notebooks.txt
      - name: Run fast notebooks (headless, no network)
        env:
          TS2EG_CI: "1"
          MPLBACKEND: "Agg"
        run: |
          python scripts/run_notebooks.py --tag fast --timeout 120
      - name: Upload executed notebooks (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: notebooks-executed
          path: artifacts/notebooks/*.executed.ipynb
